name: Build/Release OpenEVSE

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - ci_updates
  pull_request:

jobs:
  info:
    name: Get event information
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1


  build_platform_io:
    name: Build using PlatformIO
    uses: jeremypoulter/open_evse/.github/workflows/build_platformio.yml@ci_updates

  build_arduino:
    name: Build using Arduino
    uses: jeremypoulter/open_evse/.github/workflows/build_arduino.yml@ci_updates

  release:
    name: Create pre-release

    needs:
      - build_platform_io
      - build_arduino
    if: github.ref == 'refs/heads/ci_updates'

    uses: jeremypoulter/open_evse/.github/workflows/release.yml@ci_updates
